### ISSUE TITLE
TODO Mega-issue

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#1]
## TODO
Here's a basic feature roadmap for the foreseeable future
 - [x] Forward search to `/results?=term`
 - [x] Use `.env` for secrets. REGENERATE SECRETS! 
 - [x] Update the project structure
 - [x] Investigate suggest book button hover animation
 - [x] Make a design for the results page - right now, the design is focused on searching in foreign libraries, add widgets for book we currently have in stock (show their position, exact row, etc.)
 - [x] Implement result page functionality
 - [x] Book locations
 - [x] If the user clicks on a search suggestion it should take them to the results page and automatically open an extended view for the selected book
 - [x] Admin login
 - [x] NavBar
 - [x] Make design for admin panel
 - [x] Do not forget about having multiple libraries - the school might have one library on one floor and another one on a different floor
 - [x] API Authentication
 - [x] Admin panel add books
 - [x] Popups
 - [x] Admin panel remove books
 - [x] Load from ISBN
 - [x] Load cover images by isbn
 - [x] Click mouse pointer image on all div button hovers

Other features such as foreign library search will be added in a later issue.
