### ISSUE TITLE
TODO Mega-Issue Bundle 2

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#2]
Deadline: Friday June 23rd, 2023

## TODO
 - [x] NavBar updates
 - [x] Implement genres
 - [x] Result switching component (arrows) or implement infinite scrolling
 - [x] Book discovery view UI
 - [x] Book discovery view integration
 - [x] Sort by mechanics
 - [x] Admin panel list books
 - [x] Edit books in list books panel
 - [x] Add people UI
 - [x] Add people db integration
 - [x] List people
 - [ ] List people book history
 - [x] Check a book out
 - [x] Checked books UI
 - [x] Checked books integration
 - [x] Overdue books list
 - [x] Check json web token expiration on login
 - [x] Return book

## Making the design responsive
Start with the client pages,optionally implement in the admin dashboard.

 - [ ] Search box
 - [ ] Search Result Entry
 - [ ] Collapse navbar
 - [ ] Flex for app containers

... that should be it for now
