### ISSUE TITLE
TODO Mega-Issue Bundle 3

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#3]
## TODO
 - [x] Export database as csv
 - [x] Import database as csv
 - [x] Update book details UI
