### ISSUE TITLE
TODO Mega-Issue Bundle 4

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#4]
- [x] Fix List UI overlapping entry components
 - [x] Add internal notes to book entries
 - [x] Sorting mechanics (also mentioned in #2)
 - [x] Add genre component to add book
 - [x] Automatically fetch genre when searching by isbn in add book
 - [ ] Make past due checkouts appear on top and be colored red
 - [x] Deploy to GH pages
 - [x] Automatically get genre collection
 - [x] Solve google API rate limit
 - [x] Make sure when importing CSV database files that we also update algolia
 - [x] Add notes to imports and exports
 - [x] Searching for book details by isbn in `Add-Book` doesn't update field, still says `Some fields are empty`
 - [x] Add sort mechanics to other DB views
 - [x] Add admin control panel button to landing page
 - [x] Add login page button to go back
 - [x] On signout, redirect back to landing page
 - [x] In DB imports, remove entities that are not contained in the import csv
 - [x] Fix error message
 - [x] Fix backend image fetching
 - [ ] Cleanup import functions

### Security
 - [x] Implement API security
 - [ ] Implement file fetch security
 - [x] Add JWT middleware instead of what we do now
 - [x] Use headers for bearer authentication
