### ISSUE TITLE
TODO Mega-Issue Bundle 5

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#5]
- [x] Add ISBN to list book
 - [x] Remove should be possible with just name or a button in the list
 - [x] Book checkout green fields 1 and 2 are unreadable
 - [x] Add ISBNs to book details
 - [x] Book detail widget doesn't close when switching between genre pages
 - [x] Delete all button
 - [x] Delete `Nope` genre

**Comment by FilipToth** [comment]
Can't replicate bug 3 - `Book checkout green fields 1 and 2 are unreadable`.

**Comment by FilipToth** [comment]
Done!
