### ISSUE TITLE
TODO Mega-Issue Bundle 6

### ISSUE THREAD

**Issue by FilipToth** [FilipToth/ceska-library#6]
## TODO

 - [x] Add 2 separate DB or CSV import fields for author given name and author surname
 - [x] Add handling for bogus ISBNs, maybe also add a flag to book list
 - [x] Add Public Notes

**Comment by FilipToth** [comment]
The separate DB entries have been solved, no longer necessary.

**Comment by FilipToth** [comment]
Done!
